[package]
name = "rust-axum-with-google-oauth"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.1", features = ["headers", "macros"] }
chrono = { version = "0.4.23", features = ["serde"] }
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0"
serde_with = "3.0.0"
tokio = { version = "1.21.2", features = ["full"] }
mongodb = "2.4.0"
minijinja = "0.34.0"
oauth2 = "4.4.1"
uuid = "1.3"
reqwest = "0.11.18"
dotenvy = "0.15"
