services:
    rust-axum-with-google-oauth:
        container_name: rust-axum-with-google-oauth
        build:
            context: .
        ports:
            - "127.0.0.1:3011:3011"
        restart: always
        volumes:
            - type: bind
              source: ./.env
              target: /opt/.env
              read_only: true
            - type: bind
              source: ./db
              target: /opt/db
              read_only: false
